# Generated by Django 5.2.7 on 2025-10-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.TextField()),
                ('total_words', models.IntegerField()),
                ('total_time', models.FloatField()),
                ('wrong_pronunciations', models.JSONField(default=list)),
                ('speed_variation', models.JSONField(default=dict)),
                ('fluency_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
