# Generated by Django 5.2.7 on 2025-10-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speechanalysis',
            old_name='fluency_score',
            new_name='accuracy_percent',
        ),
        migrations.RenameField(
            model_name='speechanalysis',
            old_name='wrong_pronunciations',
            new_name='extra_words',
        ),
        migrations.RenameField(
            model_name='speechanalysis',
            old_name='user_text',
            new_name='recognized_text',
        ),
        migrations.RemoveField(
            model_name='speechanalysis',
            name='speed_variation',
        ),
        migrations.RemoveField(
            model_name='speechanalysis',
            name='total_time',
        ),
        migrations.RemoveField(
            model_name='speechanalysis',
            name='total_words',
        ),
        migrations.AddField(
            model_name='speechanalysis',
            name='audio_file',
            field=models.FileField(default=0, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speechanalysis',
            name='missed_words',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='speechanalysis',
            name='reference_text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
